name: 'RTheme Build'
on:
    push:
        paths:
            - '**'
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: 'Setup Git'
              run: |
                  git init
                  git pull
                  git config --local user.email "dr_hamilton@foxmail.com"
                  git config --local user.name "Ravello-H"
            - name: 'Setup nodejs'
              uses: actions/setup-node@v3
              with:
                  node-version: 'latest'
            - name: 'Install requirements'
              run: |
                  npm install
            - name: 'RPageSearch'
              continue-on-error: True
              run: |
                  cd program
                  node search.js
            - name: 'local-feed-generation'
              continue-on-error: True
              run: |
                  cd program
                  node feed.js
            - name: 'local-sitemap-generation'
              continue-on-error: True
              run: |
                  cd program
                  node fileList.js
                  npx sitemap < ../assets/data/urlList.txt > ../sitemap.xml
            - name: 'Commit files'
              continue-on-error: True
              run: |
                  git diff
                  git add -A
                  git commit -m "[RThemeBuild]`date '+%Y-%m-%d %H:%M:%S'`"
                  git status
                  git push -f
